name: Test Patterns

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer update

      - name: Run Tests
        run: composer exec phpunit

      - name: Check Code Style
        run: composer check-style

      - name: Analyze Code
        run: composer static-analyze-code
